# Generated by Django 5.1.8 on 2025-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_campaign_social_shares"),
        ("facets", "0006_alter_district_organizers"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="districts",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="facets.district"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="registered_community_organizations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="+",
                to="facets.registeredcommunityorganization",
            ),
        ),
    ]
