# Generated by Django 5.1.15 on 2026-02-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0030_petitionsignature_checkbox_responses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="update",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("past", "Completed"),
                    ("canceled", "Canceled"),
                    ("suspended", "Suspended"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
    ]
