# Generated by Django 5.1.15 on 2026-02-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0031_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="update",
            field=models.TextField(blank=True, default="Campaign complete!", null=True),
        ),
    ]
