# Generated by Django 5.1.15 on 2026-02-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0032_campaign_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="update",
            field=models.TextField(default="Campaign complete!"),
        ),
    ]
